services:
  frontend:
    container_name: bible_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: bible_backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - bible_database_volume:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  bible_database_volume: {}
